# Site settings
title: Wocker

github_user: ixkaito
github_org: wocker-prj
github_repo: wocker
facebook_user: kite.koga
twitter_user: ixkaito

baseurl: ""
url: http://wocker-prj.github.io
description: Docker-based rapid development environment of WordPress. IT TAKES JUST 3 SECONDS TO CREATE A NEW ONE!

images_dir: /assets/images
css_dir: /assets/css
js_dir: /assets/js

ogp_image: /ogp-image.png

# Build settings
markdown: redcarpet
