# Site settings
title: Wocker

github_username: ixkaito
github_repository: ixkaito/wocker
facebook_username: kite.koga
twitter_username: ixkaito

baseurl: /wocker
url: http://ixkaito.github.io
description: Wocker is a Docker-based rapid development environment of WordPress. IT TAKES JUST 3 SECONDS TO CREATE A NEW ONE!

images_dir: /assets/images
css_dir: /assets/css
js_dir: /assets/js

# Build settings
markdown: redcarpet
