# Site settings
title: Wocker

twitter_username: ixkaito
github_username:  ixkaito

baseurl: "/wocker"
url: "http://ixkaito.github.io"

images_dir: "/assets/images"
css_dir: "/assets/css"
js_dir: "/assets/js"

# Build settings
markdown: redcarpet
